trigger: none

pr:
  branches:
    include:
      - 'pr-check'

variables:
  - group: choreo-samples

steps:
  - script: echo 'Starting Pull Request Validation'
    displayName: "Starting PR Validation"

  # - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pyyaml
    displayName: "Install dependencies"

  - script: |
      python .azure/validate_samples.py
    displayName: "Sample Validation"

  # - script: |
  #     # Check the exit code of the Python script
  #     if [ $? -eq 0 ]; then
  #       echo 'Python script executed successfully.'
  #     else
  #       echo 'Python script failed. Failing the pipeline.'
  #       exit 1
  #     fi
  #   displayName: 'Check Python Script Exit Code'

  - script: echo 'Pull Request Validation Completed'
    displayName: "PR Validation Completed"
